# Generated by Django 5.1.6 on 2025-02-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralizedLaborFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('okpdtr_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LaborFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('qualification_level', models.IntegerField()),
                ('generalized_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.generalizedlaborfunction')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
            ],
        ),
        migrations.CreateModel(
            name='LaborAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('labor_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.laborfunction')),
            ],
        ),
        migrations.CreateModel(
            name='OKSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('labor_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.laborfunction')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('labor_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.laborfunction')),
            ],
        ),
    ]
