# Generated by Django 5.1.6 on 2025-02-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0003_generalizedlaborfunction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborfunction',
            name='qualification_level',
            field=models.IntegerField(choices=[(6, 'Уровень 6'), (7, 'Уровень 7')]),
        ),
    ]
