# Generated by Django 5.1.6 on 2025-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0004_alter_laborfunction_qualification_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborfunction',
            name='code',
        ),
        migrations.AddField(
            model_name='profession',
            name='code',
            field=models.CharField(default='Prof_code', max_length=20),
        ),
    ]
