# Generated by Django 5.1.6 on 2025-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0005_remove_laborfunction_code_profession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='code',
            field=models.CharField(default='Prof_code', max_length=20, unique=True),
        ),
    ]
