# Generated by Django 5.1.6 on 2025-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0006_alter_profession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
