# Generated by Django 5.1.6 on 2025-02-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0007_alter_profession_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okso',
            name='profession',
        ),
        migrations.AddField(
            model_name='okso',
            name='labor_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professions.laborfunction'),
        ),
    ]
