# Generated by Django 5.1.6 on 2025-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0008_remove_okso_profession_okso_labor_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedlaborfunction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
