# Generated by Django 5.1.6 on 2025-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0009_alter_generalizedlaborfunction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedlaborfunction',
            name='description',
            field=models.TextField(),
        ),
    ]
